title: Francesc Madrona
description: ğŸ—ï¸ Ideas into Code
google_analytics:
theme: jekyll-theme-hacker
github_account: 'https://github.com/xopino'
linkedin_account: 'https://www.linkedin.com/in/francescmadrona/'